Parameters:
    ArtifactsBucket:
        Type: String
        Default: artifacts222.bucket
        Description: S3 Bucket Name for CodeBuild Artifacts

Resources:

    # S3 Bucket for build artifacts
    BuildArtifactsBucket:
        Type: AWS::S3::Bucket
        Properties:
          AccessControl: Private
          BucketName: !Sub '${ArtifactsBucket}'
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            # BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          BucketEncryption:
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256

    BucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties: 
        Bucket: !Ref BuildArtifactsBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
              - 's3:PutBucketPolicy'
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucket}'
            Principal: '*'
          - Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucket}/*'
            Principal: '*'  
          - Action: 's3:PutObject'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': true
            Effect: Deny
            Principal: '*'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${ArtifactsBucket}/*'
            Sid: DenyPublishingUnencryptedResources            