AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an IAM Role

Parameters:
  JenkinsAwsAccountId:
    Type: Number
    Description: Account number of the AWS account to which to grant read access for
      monitoring purposes.

Resources:
  MyTestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Join [ "", [ 'arn:aws:iam::',!Ref JenkinsAwsAccountId, ':root'] ]
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide access to S3
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
      RoleName: JenkinsRole
        
Outputs: 
  RoleName: 
    Description: Name of Created IAM Role
    Value: !Ref MyTestRole  
  RoleArn: 
    Description: Arn of Created Role
    Value: !GetAtt MyTestRole.Arn    