
Parameters:
  EnvironmentName:
    Description: Name the project
    Type: String

  Identifier:
    Description: Please write the name you want your project to get Identified 
    Type: String

  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.t3.small

  DBAllocatedStorage:
    Default: '20'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '1000'
    ConstraintDescription: must be between 20 and 65536 GiB.

  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    AllowedValues: [sqlserver-ee, sqlserver-se, sqlserver-ex, sqlserver-web]
    ConstraintDescription: "Please specify either a sqlserver-ee, sqlserver-se, sqlserver-ex, or sqlserver-web engine for the RDS instance."

  MasterUsername:
    Description: Please write username
    Type: String

  MasterPassword:
    Description: Please write password (more then 8 characters)
    Type: String
    NoEcho: true

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: cambium
      Engine: !Ref Engine
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterPassword
      DBInstanceClass: !Ref DBInstanceClass
      LicenseModel: license-included
      MonitoringInterval: 0 
      PubliclyAccessible: true 
      MultiAZ: false
      Tags:
        - Key: Client
          Value: Cambium
        - Key: Name
          Value: Test
        - Key: Project
          Value: DevOps
        - Key: Chargeable
          Value: "No"      
      DBSecurityGroups:
      - Ref: DBSecurityGroup
      AllocatedStorage: !Ref DBAllocatedStorage
      MaxAllocatedStorage: 1000
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        EC2SecurityGroupName:
          Ref: WebServerSecurityGroup
      GroupDescription: Frontend Access
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3386
        ToPort: 3386
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 1433
        ToPort: 1433
        CidrIp: 0.0.0.0/0
  # DBSubnetGroup: 
  #  Type: "AWS::RDS::DBSubnetGroup"
  #  Properties:
  #   DBSubnetGroupDescription: Subnet for the database
  #   SubnetIds:
  #     - Ref : PublicSubnet1
  #     - Ref : PublicSubnet2